### 予想

5が表示される。

#### 理由

tryブロックでエラーをスローした後catchブロックに入る  
＝＞catchブロックの`break`では最も内側のブロック(catch)を抜ける  
＝＞そのままfinallyブロックに入りループが再実行される  
＝＞ループはiが5になるまで行われ、最終的に5が表示される

### 結果

5が表示される。
